#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Regenerate Utils terminal-width tables from pinned Unicode data (stdlib only)."""
from pathlib import Path
from urllib.request import urlopen

VERSION = "17.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"


def read(name):
    with urlopen(BASE + name, timeout=60) as response:
        return response.read().decode("utf-8")


def ranges(values):
    result = []
    for value in sorted(values):
        if result and result[-1][1] + 1 == value:
            result[-1][1] = value
        else:
            result.append([value, value])
    return result


def main():
    zero = set(range(0x1160, 0x1200))  # Hangul medial/final jamo join the initial cell.
    for line in read("UnicodeData.txt").splitlines():
        fields = line.split(";")
        if fields[2] in {"Mn", "Mc", "Me", "Cf"}:
            zero.add(int(fields[0], 16))
    wide = set()
    for line in read("EastAsianWidth.txt").splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        interval, width = [part.strip() for part in line.split(";")]
        if width not in {"W", "F"}:
            continue
        bounds = interval.split("..")
        wide.update(range(int(bounds[0], 16), int(bounds[-1], 16) + 1))
    with urlopen("https://www.unicode.org/license.txt", timeout=60) as response:
        license_text = response.read().decode("utf-8")
    text = "// Generated by tools/generate_unicode_width.py; do not edit.\n"
    text += f"// Unicode {VERSION}: {BASE}UnicodeData.txt and EastAsianWidth.txt\n"
    text += "// SPDX-License-Identifier: Unicode-3.0\n//\n"
    text += "\n".join("// " + line for line in license_text.splitlines()) + "\n\n"
    text += f'pub const UNICODE_VERSION: &str = "{VERSION}";\n'
    for name, values in [("ZERO_WIDTH", zero), ("WIDE", wide)]:
        text += f"pub(super) const {name}: &[(u32, u32)] = &[\n"
        text += "".join(f"    (0x{a:X}, 0x{b:X}),\n" for a, b in ranges(values))
        text += "];\n"
    output = Path(__file__).resolve().parents[1] / "utils/src/display_width_tables.rs"
    output.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
