#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Regenerate pinned trig reference vectors and check the 2/pi reduction table.

Maintenance-only dependency: mpmath 1.3.0 at 800 decimal digits. The compiler,
standard library and regression tests consume checked-in data without mpmath.
Inputs are reconstructed from their exact binary64 values before evaluation.
"""
from pathlib import Path
import math
import random
import struct
import re
import mpmath as mp


def bits(x):
    return struct.unpack(">Q", struct.pack(">d", x))[0]


def main():
    mp.mp.dps = 800
    root = Path(__file__).resolve().parents[1]
    constant = int((2 / mp.pi) * (1 << 2048))
    limbs = [(constant >> (32 * i)) & 0xFFFFFFFF for i in range(64)]
    path = root / "std/math/trig_reduction.wave"
    text = path.read_text()
    actual = [int(x) for x in re.search(r"= \[(.*?)\];", text, re.S)[1].replace("\n", "").split(",")]
    assert actual == limbs, "2/pi limbs differ from the high-precision reference"
    samples = [0.0, -0.0, 5e-324, -5e-324, 1e-300, -1e-300, 0.1, 0.7853981633974483,
               1e6, 1e12, 1e20, 1e100, 1e200, 1e300, float.fromhex("0x1.fffffffffffffp1023")]
    for n in [1, 2, 3, 4, 17, 1024, 1048576, 2**40, 2**100, 2**500, 2**1000]:
        center = float(mp.pi * n / 2)
        samples.extend([math.nextafter(center, -math.inf), center, math.nextafter(center, math.inf)])
    rng = random.Random(600)
    for exponent in range(-1022, 1024, 17):
        samples.append(math.ldexp(rng.uniform(1, 2), exponent))
    for _ in range(80):
        samples.append(math.ldexp(rng.uniform(1, 2), rng.randrange(-1, 1024)))
    samples += [-x for x in samples if x > 0]
    write_vectors(root / "tests/fixtures/native_providers/trig_reference.txt", samples)
    single = [0.0, -0.0]
    for x in samples:
        try:
            single.append(struct.unpack(">f", struct.pack(">f", x))[0])
        except OverflowError:
            pass
    for raw in [1, 0x80000001, 0x7f7fffff, 0xff7fffff, 0x3fc90fda, 0x3fc90fdb, 0x3fc90fdc,
                0x40490fda, 0x40490fdb, 0x40490fdc]:
        single.append(struct.unpack(">f", struct.pack(">I", raw))[0])
    write_vectors(root / "tests/fixtures/native_providers/trig_reference_f32.txt", single)


def write_vectors(path, samples):
    lines = ["# Generated by tools/generate_trig_vectors.py (mpmath 1.3.0, 800 digits)",
             "# Exact input, sin, cos, tan as hexadecimal binary64 bits"]
    for x in samples:
        # mpmath takes the exact binary float; do not round it through decimal text.
        exact = mp.mpf(x)
        values = [float(mp.sin(exact)), float(mp.cos(exact)), float(mp.tan(exact))]
        if x == 0:  # mpmath does not distinguish signed zero.
            values[0] = values[2] = x
        lines.append(" ".join(f"{bits(v):016x}" for v in [x, *values]))
    path.write_text("\n".join(lines) + "\n")



if __name__ == "__main__":
    main()
