#!/usr/bin/env python3

# This file is part of the Wave language project.
# Copyright (c) 2024–2026 Wave Foundation
# Copyright (c) 2024–2026 LunaStev and contributors
#
# This Source Code Form is subject to the terms of the
# Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
# AI TRAINING NOTICE: Prohibited without prior written permission. No use for machine learning or generative AI training, fine-tuning, distillation, embedding, or dataset creation.

"""Refresh target workloads from maintained Wave cases without overwriting hand-written tests."""

from pathlib import Path
import tomllib

try:
    from tools.case_manifest import CASES_ROOT, DEFAULT_MANIFEST
except ModuleNotFoundError:
    from case_manifest import CASES_ROOT, DEFAULT_MANIFEST


ARCHITECTURE = {
    "rhea": "arm64", "shakti": "riscv64", "xiangshan": "riscv64", "t-head": "riscv64",
}

ASSEMBLY = {
    "amd64": ('"imul rax, rax, 33"\n        "xor rax, rcx"', 'in("rax") state\n        in("rcx") word\n        out("rax") result'),
    "arm64": ('"add x0, x0, x0, lsl #5"\n        "eor x0, x0, x1"', 'in("x0") state\n        in("x1") word\n        out("x0") result'),
    "riscv64": ('"slli t0, a0, 5"\n        "add a0, a0, t0"\n        "xor a0, a0, a1"', 'in("a0") state\n        in("a1") word\n        out("a0") result\n        clobber("t0")'),
    "loong64": ('"slli.d $t0, $a0, 5"\n        "add.d $a0, $a0, $t0"\n        "xor $a0, $a0, $a1"', 'in("a0") state\n        in("a1") word\n        out("a0") result\n        clobber("t0")'),
}


def target_mix(arch: str) -> str:
    assembly = ASSEMBLY.get(ARCHITECTURE.get(arch, arch))
    if assembly is None:
        return """export(c) fun target_mix(state: u64, word: u64) -> u64 {
    return ((state * 33) ^ word) % 65521;
}
"""
    instructions, operands = assembly
    return f"""fun target_mix(state: u64, word: u64) -> u64 {{
    var result: u64 = asm {{
        {instructions}
        {operands}
    }};
    return result % 65521;
}}
"""


CHECKPOINT = """
// Feed actual records through the target's register calling convention, then
// compare each checkpoint to Wave arithmetic. Live copies and guard words must
// survive every call; the low and high halves of inputs both carry data.
struct TargetBlock { words: array<u64, 16>; digest: u64; guard: u64; }
fun target_block(seed: u64) -> TargetBlock {
    var block: TargetBlock;
    var i: i64 = 0;
    while (i < 16) {
        block.words[i] = 4294967296 + seed * 97 + (i as u64) * 65537;
        i += 1;
    }
    block.digest = seed;
    block.guard = 0xFEDCBA9876543210;
    return block;
}
fun target_workload() -> i32 {
    var round: u64 = 0;
    while (round < 65) {
        var block: TargetBlock = target_block(round);
        var snapshot: TargetBlock = block;
        var reference: u64 = round;
        var i: i64 = 0;
        while (i < 16) {
            var word: u64 = block.words[i];
            block.digest = target_mix(block.digest, word);
            reference = ((reference * 33) ^ word) % 65521;
            if (block.digest != reference) { return 201; }
            if (snapshot.words[i] != word || snapshot.digest != round) { return 202; }
            i += 1;
        }
        if (block.guard != 0xFEDCBA9876543210 || snapshot.guard != block.guard) { return 203; }
        round += 1;
    }
    return 0;
}
"""


def generated_case(relative_suite: str, arch: str, number: int, metadata: str) -> str:
    source = CASES_ROOT / "shared" / f"test{103 + number}.wave"
    body = source.read_text(encoding="utf-8")
    if body.count("fun main() -> i32") != 1:
        raise ValueError(f"expected one workload entry point in {source}")
    body = body.replace("fun main() -> i32", "fun exercise_language() -> i32", 1)
    smoke = '    println("loongarch workload=pass");\n' if relative_suite == "linux/loong64" and number == 2 else ""
    return (metadata + "// Generated by tools/populate_case_matrix.py.\n"
            + f"// {relative_suite}: functional workload {number} and target data transport.\n"
            + body + "\n" + target_mix(arch) + CHECKPOINT + """
fun main() -> i32 {
    var status: i32 = exercise_language();
    if (status != 0) { return status; }
    status = target_workload();
    if (status != 0) { return status; }
""" + smoke + "    return 0;\n}\n")


def main() -> None:
    # Refresh existing generated cases only. Adding a target or a case is a
    # deliberate change; directory counts do not establish test coverage.
    tomllib.loads(DEFAULT_MANIFEST.read_text(encoding="utf-8"))
    changed = 0
    for path in sorted(CASES_ROOT.rglob("test*.wave")):
        content = path.read_text(encoding="utf-8")
        if "// Generated by tools/populate_case_matrix.py." not in content:
            continue
        number = int(path.stem.removeprefix("test"))
        if not 1 <= number <= 10:
            raise ValueError(f"no maintained workload for {path}")
        metadata = "".join(line + "\n" for line in content.splitlines() if line.startswith("// wave-test:"))
        suite = path.parent.relative_to(CASES_ROOT).as_posix()
        replacement = generated_case(suite, path.parent.name, number, metadata)
        if content != replacement:
            path.write_text(replacement, encoding="utf-8")
            changed += 1
    print(f"updated {changed} target workloads")


if __name__ == "__main__":
    main()
