WHITESPACE = _{ " " | "\t" | "\n" }
program = { SOI ~ main_fn ~ EOI }
main_fn = { "fun" ~ "main" ~ "()" ~ "{" ~ stmt* ~ "}" }
stmt = _{ var_decl | expr_stmt | while_stmt }
var_decl = { "var" ~ identifier ~ "=" ~ expr }
expr_stmt = { expr }
while_stmt = { "while" ~ expr ~ "{" ~ stmt* ~ "}" }
expr = _{ number | identifier | bin_op }
number = @{ "-"? ~ ASCII_DIGIT+ }
identifier = @{ ASCII_ALPHANUMERIC+ }
bin_op = { expr ~ ("+" | "-" | "*" | "/") ~ expr }
